# Generated by Django 5.0.6 on 2024-05-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
